# Base Io build system
# Written by Jeremy Tregunna <jeremy.tregunna@me.com>
#
# Find libevent.

FIND_PATH(LIBEVENT_INCLUDE_DIR event.h)

SET(LIBEVENT_NAMES ${LIBEVENT_NAMES} event libevent)
FIND_LIBRARY(LIBEVENT_LIBRARY NAMES ${LIBEVENT_NAMES} PATH)

IF(LIBEVENT_INCLUDE_DIR AND LIBEVENT_LIBRARY)
	SET(LIBEVENT_FOUND TRUE)
ENDIF(LIBEVENT_INCLUDE_DIR AND LIBEVENT_LIBRARY)

IF(LIBEVENT_FOUND)
	IF(NOT LibEvent_FIND_QUIETLY)
		MESSAGE(STATUS "Found Event: ${LIBEVENT_LIBRARY}")
	ENDIF (NOT LibEvent_FIND_QUIETLY)
ELSE(LIBEVENT_FOUND)
	IF(LibEvent_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find event")
	ENDIF(LibEvent_FIND_REQUIRED)
ENDIF (LIBEVENT_FOUND)
